---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: .*.md
      - id: end-of-file-fixer
        exclude: .*.md

  - repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
    - id: black
