name: pylint

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  pylint:
    runs-on: ubuntu-latest
    container: robertbindar/mariadb_jupyter_kernel:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          python setup.py develop

      - name: Test with pylint
        run: |
          pylint mariadb_kernel/*.py
